version: 2.1

commands:
  description: "Coverage Tests"
  coverage_tests:
    steps:
      - add_ssh_keys:
          fingerprints:
            - ${PANTHEON_SSH_FINGERPRINT}
      - run:
          name: Checkout Pantheon repository
          command: |
            git clone ssh://codeserver.dev.${PANTHEON_SITE_ID}@codeserver.dev.${PANTHEON_SITE_ID}.drush.in:2222/~/repository.git .
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # We can use these once boostid uses git tags or is an npm module
            # - node-v1-{{ .Branch }}-
            # - node-v1-
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /app/node_modules
      - run:
          name: Coverage tests
          command: ./node_modules/boostid/scripts/run-tests.sh
      - store_artifacts:
          path: /tmp/boostid_test_results
          destination: boostid_test_results

jobs:
  upstream_updates:
    docker:
      - image: wades/boostid:0.0.1
    working_directory: /app
    steps:
      - run:
          name: Install boostid globally
          command: npm install -g wyattades/boostid
      - run:
          name: "Run upstream updates on 'updates' multidev"
          command: boostid upstream-updates
      - coverage_tests
      - run:
          name: "Merge 'updates' multidev to 'dev'"
          command: boostid ter multidevMergeToDev updates
          when: on_success
      # - run:
      #     name: "Push 'updates' branch to github"
      #     command: ./node_modules/boostid/scripts/pantheon-to-github.sh updates
      #     when: on_success

workflows:
  version: 2.1

  nightly:
    jobs:
      - upstream_updates:
          filters:
            branches:
              only: master

    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *" # Every day at 12:00am UTC
    #       filters:
    #         branches:
    #           only:
    #             - master
