version: 2.1


jobs:
  upstream_updates:
    docker:
      - image: wades/boostid:0.0.1
    working_directory: /app
    parameters:
      just_tests:
        type: boolean
        default: false
      local:
        type: boolean
        default: true
    steps:
      - add_ssh_keys
      - when:
          condition: <<parameters.local>>
          steps:
            - checkout
      - unless:
          condition: <<parameters.local>>
          steps:
            - run:
                name: Checkout Pantheon repository
                command: |
                  ssh-keyscan -p 2222 -H codeserver.dev.${BOOSTID_ID}.drush.in >> ~/.ssh/known_hosts
                  git clone ssh://codeserver.dev.${BOOSTID_ID}@codeserver.dev.${BOOSTID_ID}.drush.in:2222/~/repository.git .
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # We can use these once boostid uses git tags or is an npm module
            # - node-v1-{{ .Branch }}-
            # - node-v1-
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - unless:
          condition: <<parameters.just_tests>>
          steps:
            - run:
                name: Run updates and coverage tests
                command: ./node_modules/boostid/scripts/run-updates.js
      - when:
          condition: <<parameters.just_tests>>
          steps:
            - run:
                name: Run coverage tests
                command: |
                  ./node_modules/boostid/scripts/run-tests.sh || (node -e "require('./node_modules/boostid/lib/reporter')(true)"; false)
          path: /tmp/boostid_results_url
          destination: boostid_results_url


workflows:
  nightly:
    jobs:
      - upstream_updates:
          local: false
          just_tests: true
          filters:
            branches:
              only: master

    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *" # Every day at 12:00am UTC
    #       filters:
    #         branches:
    #           only:
    #             - master