version: 2.1


jobs:
  upstream_updates:
    docker:
      - image: wades/boostid:0.0.1
    working_directory: /app
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${BOOSTID_SSH_FINGERPRINT}"
      - run:
          name: Checkout Pantheon repository
          command: |
            git clone ssh://codeserver.dev.${BOOSTID_ID}@codeserver.dev.${BOOSTID_ID}.drush.in:2222/~/repository.git .
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            # We can use these once boostid uses git tags or is an npm module
            # - node-v1-{{ .Branch }}-
            # - node-v1-
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /app/node_modules
      - run:
          name: Run updates and coverage tests
          command: ./node_modules/boostid/scripts/run-updates.js
      - store_artifacts:
          path: /tmp/boostid_test_results
          destination: boostid_test_results


workflows:
  version: 2.1

  nightly:
    jobs:
      - upstream_updates:
          filters:
            branches:
              only: master

    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *" # Every day at 12:00am UTC
    #       filters:
    #         branches:
    #           only:
    #             - master
